// SPDX-License-Identifier: Apache-2.0

`timescale 1ns/1ps
`default_nettype none

module tb_ascon_block32_adapters;
  localparam integer N_WORDS = 22;

  reg clk;
  reg rst_n;
  reg clear_i;

  reg         src_valid;
  wire        src_ready;
  reg [31:0]  src_data;
  reg [2:0]   src_bytes;
  reg         src_last;

  wire        block_valid;
  wire        block_ready;
  wire [127:0] block_data;
  wire [4:0]   block_bytes;

  wire        out_valid;
  reg         out_ready;
  wire [31:0] out_data;
  wire [2:0]  out_bytes;
  wire        out_last;

  wire [1:0] pack_fill_words;
  wire [4:0] pack_fill_bytes;
  wire       pack_pending;
  wire       unpack_active;
  wire [1:0] unpack_word_index;
  wire [2:0] unpack_words_left;

  reg [31:0] exp_data  [0:N_WORDS-1];
  reg [2:0]  exp_bytes [0:N_WORDS-1];
  reg        exp_last  [0:N_WORDS-1];

  integer send_idx;
  integer recv_idx;
  integer cycle;
  integer errors;
  integer i;

  reg tb_in_fire;
  reg tb_out_fire;
  reg [31:0] tb_out_data;
  reg [2:0]  tb_out_bytes;
  reg        tb_out_last;

  ascon_block_packer32 u_packer (
    .clk            (clk),
    .rst_n          (rst_n),
    .clear_i        (clear_i),
    .word_valid_i   (src_valid),
    .word_ready_o   (src_ready),
    .word_data_i    (src_data),
    .word_bytes_i   (src_bytes),
    .word_last_i    (src_last),
    .block_valid_o  (block_valid),
    .block_ready_i  (block_ready),
    .block_data_o   (block_data),
    .block_bytes_o  (block_bytes),
    .fill_words_o   (pack_fill_words),
    .fill_bytes_o   (pack_fill_bytes),
    .block_pending_o(pack_pending)
  );

  ascon_block_unpacker32 u_unpacker (
    .clk            (clk),
    .rst_n          (rst_n),
    .clear_i        (clear_i),
    .block_valid_i  (block_valid),
    .block_ready_o  (block_ready),
    .block_data_i   (block_data),
    .block_bytes_i  (block_bytes),
    .word_valid_o   (out_valid),
    .word_ready_i   (out_ready),
    .word_data_o    (out_data),
    .word_bytes_o   (out_bytes),
    .word_last_o    (out_last),
    .active_o       (unpack_active),
    .word_index_o   (unpack_word_index),
    .words_left_o   (unpack_words_left)
  );

  always #5 clk = !clk;

  function [31:0] make_word;
    input [31:0] idx;
    begin
      make_word = 32'ha500_1000 ^ (idx * 32'h0101_0021);
    end
  endfunction

  task set_word;
    input integer idx;
    input [2:0] bytes;
    input last;
    reg [31:0] raw;
    begin
      raw = make_word(idx[31:0]);
      exp_bytes[idx] = bytes;
      exp_last[idx]  = last;
      case (bytes)
        3'd1: exp_data[idx] = {24'd0, raw[7:0]};
        3'd2: exp_data[idx] = {16'd0, raw[15:0]};
        3'd3: exp_data[idx] = {8'd0,  raw[23:0]};
        default: exp_data[idx] = raw;
      endcase
    end
  endtask

  initial begin
    // Blocks generated by this sequence:
    //   words 0..3      full block emitted automatically
    //   word 4          one-word partial block
    //   words 5..6      two-word partial block
    //   words 7..9      three-word partial block
    //   words 10..13    full block with explicit last on word 13
    //   words 14..17    full block emitted automatically
    //   words 18..21    final full block with explicit last
    set_word(0,  3'd4, 1'b0);
    set_word(1,  3'd4, 1'b0);
    set_word(2,  3'd4, 1'b0);
    set_word(3,  3'd4, 1'b1);
    set_word(4,  3'd3, 1'b1);
    set_word(5,  3'd4, 1'b0);
    set_word(6,  3'd2, 1'b1);
    set_word(7,  3'd4, 1'b0);
    set_word(8,  3'd4, 1'b0);
    set_word(9,  3'd1, 1'b1);
    set_word(10, 3'd4, 1'b0);
    set_word(11, 3'd4, 1'b0);
    set_word(12, 3'd4, 1'b0);
    set_word(13, 3'd4, 1'b1);
    set_word(14, 3'd4, 1'b0);
    set_word(15, 3'd4, 1'b0);
    set_word(16, 3'd4, 1'b0);
    set_word(17, 3'd4, 1'b1);
    set_word(18, 3'd4, 1'b0);
    set_word(19, 3'd4, 1'b0);
    set_word(20, 3'd4, 1'b0);
    set_word(21, 3'd4, 1'b1);
  end

  initial begin
    clk = 1'b0;
    rst_n = 1'b0;
    clear_i = 1'b0;
    src_valid = 1'b0;
    src_data = 32'd0;
    src_bytes = 3'd0;
    src_last = 1'b0;
    out_ready = 1'b0;
    send_idx = 0;
    recv_idx = 0;
    cycle = 0;
    errors = 0;

    repeat (4) @(posedge clk);
    rst_n = 1'b1;

    while (recv_idx < N_WORDS && cycle < 1000) begin
      @(negedge clk);
      cycle = cycle + 1;

      src_valid = (send_idx < N_WORDS) && ((cycle % 6) != 2);
      src_data  = (send_idx < N_WORDS) ? exp_data[send_idx] : 32'd0;
      src_bytes = (send_idx < N_WORDS) ? exp_bytes[send_idx] : 3'd0;
      src_last  = (send_idx < N_WORDS) ? exp_last[send_idx] : 1'b0;
      out_ready = ((cycle % 5) != 1) && ((cycle % 11) != 7);

      #1;
      tb_in_fire   = src_valid && src_ready;
      tb_out_fire  = out_valid && out_ready;
      tb_out_data  = out_data;
      tb_out_bytes = out_bytes;
      tb_out_last  = out_last;

      @(posedge clk);
      #1;

      if (tb_in_fire) begin
        send_idx = send_idx + 1;
      end

      if (tb_out_fire) begin
        if (tb_out_data !== exp_data[recv_idx]) begin
          $display("FAIL word %0d data expected=%h got=%h", recv_idx, exp_data[recv_idx], tb_out_data);
          errors = errors + 1;
        end
        if (tb_out_bytes !== exp_bytes[recv_idx]) begin
          $display("FAIL word %0d bytes expected=%0d got=%0d", recv_idx, exp_bytes[recv_idx], tb_out_bytes);
          errors = errors + 1;
        end
        if (tb_out_last !== exp_last[recv_idx]) begin
          $display("FAIL word %0d last expected=%b got=%b", recv_idx, exp_last[recv_idx], tb_out_last);
          errors = errors + 1;
        end
        recv_idx = recv_idx + 1;
      end

      if (pack_fill_bytes > 5'd15) begin
        $display("FAIL packer fill_bytes overflow: %0d", pack_fill_bytes);
        errors = errors + 1;
      end
    end

    src_valid = 1'b0;
    out_ready = 1'b0;

    if (cycle >= 1000) begin
      $display("FAIL block32 adapter timeout send=%0d recv=%0d", send_idx, recv_idx);
      errors = errors + 1;
    end

    // Clear should reset both sides cleanly.
    @(negedge clk);
    clear_i = 1'b1;
    @(posedge clk);
    #1;
    clear_i = 1'b0;
    if (pack_fill_words != 2'd0 || pack_fill_bytes != 5'd0 || pack_pending || unpack_active) begin
      $display("FAIL clear pack_words=%0d pack_bytes=%0d pending=%b unpack_active=%b",
               pack_fill_words, pack_fill_bytes, pack_pending, unpack_active);
      errors = errors + 1;
    end

    if (errors == 0) begin
      $display("ALL 32-BIT BLOCK ADAPTER TESTS PASSED");
    end else begin
      $display("32-BIT BLOCK ADAPTER TESTS FAILED errors=%0d", errors);
      $fatal;
    end

    $finish;
  end

endmodule

`default_nettype wire
