#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Minimal ASCON permutation mirror for Phase 1 RTL bring-up.

The project-level golden reference is ascon/ascon-c. This Python file mirrors
its word-level permutation so that tests can run even when the ascon-c source
is not currently available. Prefer `make vectors-ascon-c` when possible.
"""

MASK64 = (1 << 64) - 1
ROUND_CONSTANTS = [0xF0, 0xE1, 0xD2, 0xC3, 0xB4, 0xA5, 0x96, 0x87, 0x78, 0x69, 0x5A, 0x4B]


def ror64(x: int, n: int) -> int:
    x &= MASK64
    return ((x >> n) | (x << (64 - n))) & MASK64


def unpack_state(state: int) -> tuple[int, int, int, int, int]:
    return (
        (state >> 256) & MASK64,
        (state >> 192) & MASK64,
        (state >> 128) & MASK64,
        (state >> 64) & MASK64,
        state & MASK64,
    )


def pack_state(x0: int, x1: int, x2: int, x3: int, x4: int) -> int:
    return (
        ((x0 & MASK64) << 256)
        | ((x1 & MASK64) << 192)
        | ((x2 & MASK64) << 128)
        | ((x3 & MASK64) << 64)
        | (x4 & MASK64)
    )


def round_ascon(state: int, rc: int) -> int:
    x0, x1, x2, x3, x4 = unpack_state(state)

    x2 ^= rc
    x0 ^= x4
    x4 ^= x3
    x2 ^= x1

    t0 = x0 ^ ((~x1) & x2)
    t2 = x2 ^ ((~x3) & x4)
    t4 = x4 ^ ((~x0) & x1)
    t1 = x1 ^ ((~x2) & x3)
    t3 = x3 ^ ((~x4) & x0)

    t1 ^= t0
    t3 ^= t2
    t0 ^= t4

    y0 = t0 ^ ror64(t0, 19) ^ ror64(t0, 28)
    y1 = t1 ^ ror64(t1, 61) ^ ror64(t1, 39)
    y2 = ~(t2 ^ ror64(t2, 1) ^ ror64(t2, 6))
    y3 = t3 ^ ror64(t3, 10) ^ ror64(t3, 17)
    y4 = t4 ^ ror64(t4, 7) ^ ror64(t4, 41)

    return pack_state(y0, y1, y2, y3, y4)


def permute(state: int, rounds: int) -> int:
    if rounds not in (6, 8, 12):
        raise ValueError(f"unsupported ASCON round count: {rounds}")
    start = 12 - rounds
    for rc in ROUND_CONSTANTS[start:]:
        state = round_ascon(state, rc)
    return state


def hex320(x: int) -> str:
    return f"320'h{x & ((1 << 320) - 1):080x}"


def emit_verilog_vectors() -> str:
    zero = 0
    sample = int(
        "0123456789abcdeffedcba987654321000112233445566778899aabbccddeeff0f1e2d3c4b5a6978",
        16,
    )
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Auto-generated by sim/python/ascon_perm_model.py.",
        "// Prefer vectors generated from ascon/ascon-c when ASCON_C_DIR is available.",
        "",
        f"localparam [319:0] VEC_ZERO_STATE      = {hex320(zero)};",
        f"localparam [319:0] VEC_ZERO_P12        = {hex320(permute(zero, 12))};",
        f"localparam [319:0] VEC_ZERO_P8         = {hex320(permute(zero, 8))};",
        f"localparam [319:0] VEC_ZERO_P6         = {hex320(permute(zero, 6))};",
        "",
        f"localparam [319:0] VEC_SAMPLE_STATE    = {hex320(sample)};",
        f"localparam [319:0] VEC_SAMPLE_P12      = {hex320(permute(sample, 12))};",
        f"localparam [319:0] VEC_SAMPLE_P8       = {hex320(permute(sample, 8))};",
        f"localparam [319:0] VEC_SAMPLE_P6       = {hex320(permute(sample, 6))};",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    print(emit_verilog_vectors())
